services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped
    ports:
      - "9925:9000"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
      ALLOW_SIGNUP: "false"
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: http://recipes.alexandrurosu.com
    volumes:
      - /mnt/ssd/recipes:/app/data
