services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
    container_name: speedtest-tracker
    ports:
      - 8080:80
      - 8443:443
    environment:
      - PUID=1000
      - PGID=1000
      - APP_KEY=${SPEEDTEST_TRACKER_APP_KEY}
      - APP_URL=http://16.242.6.136:8080
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE="0 * * * *"
      - DISPLAY_TIMEZONE="America/New_York"
    volumes:
      - /home/arosu/stuypi-services/speedtest-tracker/config:/config
