services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - /home/arosu/stuypi-services/homepage/config:/app/config
      - /home/arosu/stuypi-services/homepage/images:/app/public/images:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      HOMEPAGE_ALLOWED_HOSTS: 16.242.6.136:3000,stuypi.alexandrurosu.com  # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
      HOMEPAGE_VAR_IMMICH_API_KEY: ${IMMICH_API_KEY}
      HOMEPAGE_VAR_BESZEL_PASSWORD: ${BESZEL_PASSWORD}
      HOMEPAGE_VAR_PIHOLE_PASSWORD: ${PIHOLE_PASSWORD}
      HOMEPAGE_VAR_PLEX_TOKEN: ${PLEX_TOKEN}
      HOMEPAGE_VAR_SPEEDTEST_TRACKER_API_KEY: ${SPEEDTEST_TRACKER_API_KEY}
      HOMEPAGE_VAR_SONARR_API_KEY: ${SONARR_API_KEY}
      HOMEPAGE_VAR_RADARR_API_KEY: ${RADARR_API_KEY}
      HOMEPAGE_VAR_PROWLARR_API_KEY: ${PROWLARR_API_KEY}
      HOMEPAGE_VAR_SABNZBD_API_KEY: ${SABNZBD_API_KEY}
      HOMEPAGE_VAR_BAZARR_API_KEY: ${BAZARR_API_KEY}
      HOMEPAGE_VAR_MEALIE_API_KEY: ${MEALIE_API_KEY}
      HOMEPAGE_VAR_HASS_TOKEN: ${HASS_TOKEN}
