services:
  kitchenowl:
    image: tombursch/kitchenowl:latest
    container_name: kitchenowl
    restart: unless-stopped
    ports:
      - "9926:8080"
    environment:
      JWT_SECRET_KEY: ${KITCHENOWL_JWT_SECRET}
      FRONT_URL: https://kitchen.alexandrurosu.com
      TZ: America/New_York
    volumes:
      - /mnt/ssd/kitchenowl:/data
