good_night:
  sequence:
  - action: light.turn_off
    target:
      entity_id:
      - light.couch
      - light.hallway
      - light.lamp
      - light.nightstand
      - light.towel_heater
      - light.office_ac
    data:
      transition: 1
  - action: fan.turn_off
    target:
      entity_id: fan.purifier_cool_e_series_tp07_tp09
  - action: light.turn_on
    target:
      entity_id:
      - light.bedroom_ac
    data: {}
  - action: fan.turn_on
    target:
      entity_id: fan.fan_2
    data:
      percentage: 100
      preset_mode: normal
  - action: media_player.turn_off
    target:
      entity_id:
      - media_player.5e_pod
      - media_player.living_room
  alias: Good Night
  description: ''
good_morning:
  sequence:
  - parallel:
    - action: light.turn_on
      target:
        entity_id: light.couch
      data:
        brightness_pct: 100
        transition: 1
    - action: light.turn_on
      target:
        entity_id: light.hallway
      data:
        brightness_pct: 100
        transition: 1
    - action: light.turn_off
      target:
        entity_id:
        - light.bedroom_ac
        - light.office_ac
        - light.lamp
        - light.nightstand
        - light.towel_heater
    - action: fan.turn_off
      target:
        entity_id: fan.fan_2
      data: {}
  alias: Good Morning
  description: ''
good_evening:
  sequence:
  - parallel:
    - action: light.turn_on
      target:
        entity_id: light.couch
      data:
        brightness_pct: 100
        transition: 1
    - action: light.turn_on
      target:
        entity_id: light.hallway
      data:
        brightness_pct: 60
        transition: 1
    - action: light.turn_on
      target:
        entity_id: light.lamp
      data:
        brightness_pct: 60
        transition: 1
    - action: light.turn_on
      target:
        entity_id: light.nightstand
      data:
        brightness_pct: 100
        transition: 1
  alias: Good Evening
  description: ''
