# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/
- General:
    - Home Assistant:
        icon: home-assistant.png
        href: https://home.alexandrurosu.com
        widget:
          type: homeassistant
          url: http://16.242.6.136:8123
          key: "{{HOMEPAGE_VAR_HASS_TOKEN}}"
    - Immich:
        icon: immich.png
        href: https://photos.alexandrurosu.com
        widgets:
          - type: customapi
            display: block
            columns: 4
            url: http://16.242.6.136:2283/api/server/statistics
            headers:
              x-api-key: "{{HOMEPAGE_VAR_IMMICH_API_KEY}}"
              Accept: application/json
            mappings:
              - field: usageByUser.0.userName
                format: text
              - field: usageByUser.0.photos
                label: Photos
                format: number
              - field: usageByUser.0.videos
                label: Videos
                format: number
              - field: usageByUser.0.usage
                label: Usage
                format: bytes
          - type: customapi
            display: block
            columns: 4
            url: http://16.242.6.136:2283/api/server/statistics
            headers:
              x-api-key: "{{HOMEPAGE_VAR_IMMICH_API_KEY}}"
              Accept: application/json
            mappings:
              - field: usageByUser.1.userName
                format: text
              - field: usageByUser.1.photos
                label: Photos
                format: number
              - field: usageByUser.1.videos
                label: Videos
                format: number
              - field: usageByUser.1.usage
                label: Usage
                format: bytes
    - Plex:
        icon: plex.png
        href: https://watch.alexandrurosu.com
        widget:
          type: plex
          url: http://16.242.6.136:32400
          key: "{{HOMEPAGE_VAR_PLEX_TOKEN}}"
          fields: ["streams", "movies", "tv"]
    - Mealie:
        icon: mealie.png
        href: https://recipes.alexandrurosu.com
        description: Recipes
        widget:
          type: mealie
          url: http://16.242.6.136:9925
          key: "{{HOMEPAGE_VAR_MEALIE_API_KEY}}"
          version: 2
- System:
    - Uptime Kuma:
        icon: uptime-kuma.png
        href: https://status.alexandrurosu.com
        widget:
          type: uptimekuma
          url: http://16.242.6.136:3001
          slug: stuypi
    - Beszel:
        icon: beszel-light.png
        href: https://metrics.alexandrurosu.com/system/r5eutb4cgcolc4t
        widget:
          type: beszel
          url: http://16.242.6.136:8090
          username: mail@alexandrurosu.com
          password: "{{HOMEPAGE_VAR_BESZEL_PASSWORD}}"
          systemId: stuypi
          version: 2
    - Speedtest Tracker:
        icon: speedtest-tracker.png
        href: https://speedtest.alexandrurosu.com
        widget:
          type: speedtest
          url: http://16.242.6.136:8080
          version: 1
          key: "{{HOMEPAGE_VAR_SPEEDTEST_TRACKER_API_KEY}}"
          bitratePrecision: 3
    - Pi-hole:
        icon: pi-hole.png
        href: https://pihole.alexandrurosu.com
        widget:
          type: pihole
          url: http://16.242.6.136:8083
          version: 6
          key: "{{HOMEPAGE_VAR_PIHOLE_PASSWORD}}"
- Arr Stack:
    - SABnzbd:
        icon: sabnzbd.png
        href: http://16.242.6.136:8181
        widget:
          type: sabnzbd
          url: http://16.242.6.136:8181
          key: "{{HOMEPAGE_VAR_SABNZBD_API_KEY}}"
- Arrs:
    - Sonarr:
        icon: sonarr.png
        href: http://16.242.6.136:8989
        widget:
          type: sonarr
          url: http://16.242.6.136:8989
          key: "{{HOMEPAGE_VAR_SONARR_API_KEY}}"
    - Radarr:
        icon: radarr.png
        href: http://16.242.6.136:7878
        widget:
          type: radarr
          url: http://16.242.6.136:7878
          key: "{{HOMEPAGE_VAR_RADARR_API_KEY}}"
    - Prowlarr:
        icon: prowlarr.png
        href: http://16.242.6.136:9696
        widget:
          type: prowlarr
          url: http://16.242.6.136:9696
          key: "{{HOMEPAGE_VAR_PROWLARR_API_KEY}}"
    - Bazarr:
        icon: bazarr.png
        href: http://16.242.6.136:6767
        widget:
          type: bazarr
          url: http://16.242.6.136:6767
          key: "{{HOMEPAGE_VAR_BAZARR_API_KEY}}"
