# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
title: stuypi
favicon: /images/favicon.ico
layout:
  Media:
    style: row
providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
