# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
title: stuypi
favicon: /images/favicon.ico
layout:
  General:
    style: row
  System:
    style: row
  Arr Stack:
    style: row
    columns: 1
  Arrs:
    style: row
    columns: 2
    header: false
providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
